### ISSUE TITLE
SQL error after plugin upgrade

### ISSUE THREAD

**Issue by 01Kuzma** [wintercms/wn-user-plugin#34]
Hello!
I continue to replace the rainlab's plugins with winter.
Rainlab's user plugin version `1.64`
I've removed the plugin's folder and installed the Winter user plugin.
This error is generated:
`"SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists (SQL: create table `users` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) null, `email` varchar(255) not null, `password` varchar(255) not null, `activation_code` varchar(255) null, `persist_code` varchar(255) null, `reset_password_code` varchar(255) null, `permissions` text null, `is_activated` tinyint(1) not null default '0', `activated_at` timestamp null, `last_login` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB)" on line 760 of C:\laragon\www\winter3\vendor\laravel\framework\src\Illuminate\Database\Connection.php`

**Comment by mjauvin** [comment]
php artisan migrate

**Comment by 01Kuzma** [comment]
@mjauvin , thank you, but I'm getting this error:
`SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists (SQL: create table `users` (`
  id` int unsigned not null auto_increment primary key, `name` varchar(255) null, `email` varchar(255) not null, `pas
  sword` varchar(255) not null, `activation_code` varchar(255) null, `persist_code` varchar(255) null, `reset_passwor
  d_code` varchar(255) null, `permissions` text null, `is_activated` tinyint(1) not null default '0', `activated_at`
  timestamp null, `last_login` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default char
  acter set utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB)`

![image](https://user-images.githubusercontent.com/569504/224793095-edc96e8a-6e4f-41c9-a54f-9e18abe353c2.png)

**Comment by mjauvin** [comment]
I don't know, what version of Rainlab.User did you migrate from ?

**Comment by mjauvin** [comment]
Try changing the "replace" config in Winter.User's composer.json to "~1.6" and run "php artisan migrate" again.

**Comment by 01Kuzma** [comment]
Strange, but there is no Winter.User.
My composer.json: 
```
{
    "name": "wintercms/winter",
    "description": "Free, open-source, self-hosted CMS platform based on the Laravel PHP Framework. Originally known as October CMS.",
    "homepage": "https://wintercms.com",
    "type": "project",
    "keywords": ["winter", "cms", "wintercms", "laravel", "cmf"],
    "license": "MIT",
    "authors": [
        {
            "name": "Alexey Bobkov",
            "email": "aleksey.bobkov@gmail.com",
            "role": "Original Author"
        },
        {
            "name": "Samuel Georges",
            "email": "daftspunky@gmail.com",
            "role": "Original Author"
        },
        {
            "name": "Luke Towers",
            "email": "wintercms@luketowers.ca",
            "role": "Lead Maintainer"
        }
    ],
    "support": {
        "issues": "https://github.com/wintercms/winter/issues",
        "docs": "https://wintercms.github.io/docs/",
        "discord": "https://discord.gg/D5MFSPH6Ux",
        "source": "https://github.com/wintercms/winter"
    },
    "require": {
        "php": "^8.0.2",
        "winter/storm": "dev-develop as 1.2",
        "winter/wn-system-module": "dev-develop",
        "winter/wn-backend-module": "dev-develop",
        "winter/wn-cms-module": "dev-develop",
        "laravel/framework": "^9.1",
        "wikimedia/composer-merge-plugin": "~2.0.1",
        "offline/oc-responsiveimages-plugin": "dev-develop",
        "winter/wn-blog-plugin": "^2.1",
        "winter/wn-pages-plugin": "^2.1",
        "winter/wn-sitemap-plugin": "^2.0"
    },
    "require-dev": {
        "phpunit/phpunit": "^9.5.8",
        "mockery/mockery": "^1.4.4",
        "fakerphp/faker": "^1.9.2",
        "squizlabs/php_codesniffer": "^3.2",
        "php-parallel-lint/php-parallel-lint": "^1.0",
        "dms/phpunit-arraysubset-asserts": "^0.1.0|^0.2.1"
    },
    "scripts": {
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-update-cmd": [
            "@php artisan winter:version",
            "@php artisan package:discover"
        ],
        "test": [
            "phpunit --stop-on-failure"
        ],
        "lint": [
            "parallel-lint --exclude vendor --exclude storage --exclude modules/system/tests/fixtures/plugins/testvendor/goto/Plugin.php ."
        ],
        "sniff": [
            "phpcs --colors -nq --report=\"full\" --extensions=\"php\""
        ]
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "merge-plugin": {
            "include": [
                "plugins/myauthor/*/composer.json"
            ],
            "recurse": true,
            "replace": false,
            "merge-dev": false
        }
    },
    "config": {
        "allow-plugins": {
            "composer/installers": true,
            "wikimedia/composer-merge-plugin": true,
            "kylekatarnls/update-helper": true
        }
    }
}

```

**Comment by 01Kuzma** [comment]
@mjauvin any thoughts?
It seems, that the upgrade is completed partially. I'm able to open the Users tab in the backend.

**Comment by mjauvin** [comment]
What does "php artisan plugin:list" outputs?

**Comment by 01Kuzma** [comment]
Here is  a screenshot:
![image](https://user-images.githubusercontent.com/569504/225077573-50a2818d-122e-4e3b-9efe-6188cd44e2cf.png)

**Comment by jaxwilko** [comment]
We're probably targeting a earlier version in our Winter.User's Plugin.php, you could try changing it but i'm not sure how compatibility would work

**Comment by mjauvin** [comment]
@01Kuzma what do you have in Winter.User's Plugin.php file for this:
```
            'replaces'    => ['RainLab.User' => '~1.6'],
```

**Comment by 01Kuzma** [comment]
I've replaced it with your's suggested line and it seems to work.
The plugin is upgraded to `2.0.0`
Thank you!

**Comment by mjauvin** [comment]
That means you don't have the latest version of the plugin I guess.

**Comment by 01Kuzma** [comment]
hm, indeed, the latest version in repo is 2.1, mine is 2.0.
Which composer command should I run to test for the latest version? `composer update`?

**Comment by 01Kuzma** [comment]
for an unknown reason, it doesn't contain the `winter.user`, you could check it [here](https://github.com/wintercms/wn-user-plugin/issues/34#issuecomment-1466707082)

**Comment by mjauvin** [comment]
How did you install it, then ?

**Comment by 01Kuzma** [comment]
as I remember, with `composer require winter/wn-user-plugin`

**Comment by mjauvin** [comment]
> as I remember, with `composer require winter/wn-user-plugin`

If that were the case, it would be in your composer.json file.

You can also add it manually.

**Comment by 01Kuzma** [comment]
Thank you!
 I've added `"winter/wn-user-plugin": "^2.0"` to `composer.json`
Then ran `composer:update` and `php artisan migrate`
