### ISSUE TITLE
Password confirmation doesn't match

### ISSUE THREAD

**Issue by slsxo** [wintercms/wn-user-plugin#36]
Hey. Using latest versions of wintercms and plugins, getting this "Password confirmation doesn't match" in Sign Up form.
Debug $user in vendor/winter/storm/src/Auth/Manager.php at line 138 right after filling model shows that password already hashed but password_confirmation obviously not.

![image](https://user-images.githubusercontent.com/104219168/230666711-690c765f-196d-4d27-aacc-968222d8243e.png)

And btw, this validation error doesn't prevent user of being created.

Any workarounds?

EDIT:
Just debugged $user entity in beforeValidate() hook in plugins/winter/user/models/User.php at line 242, situation the same, password already hashed but password_confirmation not.

EDIT:
Had issue here, but still im courious about why i see validation error instead of actual in event handler.
`      
Event::listen('winter.user.activate', function ($user) {
    ...
});
`

**Comment by LukeTowers** [comment]
@slsxo I'm not sure I understand what the problem was and what your fix was. Do you have any other comments on this issue?
