### ISSUE TITLE
Call to undefined method Illuminate\Mail\Message::setTo()

### ISSUE THREAD

**Issue by 8blvck** [wintercms/wn-user-plugin#37]
https://github.com/wintercms/wn-user-plugin/blob/4d8e2b4bd1c75b687d8ac0390b0ff6d2fabeb942/models/MailBlocker.php#L263

Error occurs if we have blocked emails.

**Comment by 8blvck** [comment]
My quick fix, just in case.
```php
$message->forgetTo();
$message->to($recipients);
```

**Comment by bennothommo** [comment]
Tracking the issue here: https://github.com/wintercms/winter/issues/888.
