### ISSUE TITLE
Class not found without Notify plugin installed

### ISSUE THREAD

**Issue by rubenvanerk** [wintercms/wn-user-plugin#8]
- Plugin version: a60045b
- Winter CMS Build: 203d2c4
- PHP Version: 8.0.6
- Plugins Installed: Flynsarmy.IdeHelper, Winter.Builder, Winter.Debugbar

I wanted to make use of the `registerClassAliases` function, so I updated to https://github.com/wintercms/wn-user-plugin/commit/a60045b2dd87f607111db5c731e5c7d9447b33d0.
When composer runs the `php artisan winter:version` command, I'm getting the following error: ` Class "Winter\User\Classes\UserEventBase" not found`

This error does not occur when I have the Notify plugin installed.

**Comment by mjauvin** [comment]
yes, we are aware of the problem and @bennothommo has a working solution for this, currently in the testing phase.

**Comment by bennothommo** [comment]
@rubenvanerk This should be fixed in Winter CMS 1.1.4 and above. If it's still happening, please let me know and I'll re-open this issue.
